# Site settings
author: Oliver Bebber
title: 
header-img: img/home-bg.png
email: ogbebber@gmail.com
copyright_name: Oliver Bebber
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  oliverbebber

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
